flowchart TD
    A(Make and buy parts complete) --> B[Assemble battery cradle - A1]
    A --> C[Assembly Load cells storage - A6]
    A --> D[Top Panel assembly - A3]
    A --> E[PCB Mount assembly - A2]
    E --> F
    B --> F[Basin assembly - A4]
    C --> I
    F --> G[Electronics housing assembly - A6]
    D --> G
    A --> H[Pelican case ports assembly - A7]
    H --> I[Lower pelican case assembly - A8]
    G --> I
    I --> J[Final assembly - A9]
